# -*- coding: utf-8 -*-
"""RSI_GRAPHIQUE.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3MX1SSO2zTg4w8K4pmPZ-ToowkddgwT
"""

import yfinance as yf
import matplotlib.pyplot as plt

# Télécharger les données d'une action
data = yf.download("BABA", start="2023-01-01", end="2025-09-30")

# Calcul du RSI
window = 14
delta = data["Close"].diff()
gain = delta.where(delta > 0, 0)
loss = -delta.where(delta < 0, 0)

avg_gain = gain.rolling(window=window).mean()
avg_loss = loss.rolling(window=window).mean()

rs = avg_gain / avg_loss
rsi = 100 - (100 / (1 + rs))

# Ajouter le RSI
data["RSI"] = rsi

# Graphique
plt.figure(figsize=(12,8))

# Prix de clôture
plt.subplot(2,1,1)
plt.plot(data.index, data["Close"], label="Close Price")
plt.title("Prix et RSI")
plt.legend()

# RSI
plt.subplot(2,1,2)
plt.plot(data.index, data["RSI"], label="RSI", color="orange")
plt.axhline(70, color="red", linestyle="--")
plt.axhline(30, color="green", linestyle="--")
plt.title("Relative Strength Index (RSI)")
plt.legend()

plt.tight_layout()
#Graphique show
plt.show()